Enable CI
coredump-ch/rgb-led-firmware pull request #3
Opened 2016-10-15 16:44 UTC by dns2utf8

2016-10-15 16:46 UTC, dns2utf8 commented
@dbrgn can you enable https://travis-ci.org/coredump-ch/rgb-led-firmware

2016-10-16 11:29 UTC, dbrgn commented
Done :)

2016-10-17 09:49 UTC, rnestler requested changes
What should this do exactly? It seems to build some examples and not our firmware.
Also take a look at [arduino-builder](https://github.com/arduino/arduino-builder). It's included with the default Arduino installation.

2016-10-17 09:49 UTC, rnestler commented on .travis.yml
> +  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
Why such an old Arduino version?

2016-10-17 09:49 UTC, rnestler commented on .travis.yml
> +  - arduino --verify --board arduino:avr:uno $PWD/examples/FONAtest/FONAtest.ino
This is the wrong board. We use the Arduino nano.

2016-10-17 09:49 UTC, rnestler commented on .travis.yml
> +  - sleep 3
Why do we need an X-Server? We should use arduino-builder, which is a CLI app.

2016-10-17 09:55 UTC, dbrgn commented on .travis.yml
> +  - arduino --verify --board arduino:avr:uno $PWD/examples/FONAtest/FONAtest.ino
Doesn't really matter for the build process itself though.

2016-10-17 11:11 UTC, rnestler commented on .travis.yml
> +  - arduino --verify --board arduino:avr:uno $PWD/examples/FONAtest/FONAtest.ino
It does if we start using board specific stuff.

2016-10-17 21:24 UTC, rnestler approved these changes

2016-10-17 21:46 UTC, ubruhin commented on .travis.yml
> +language: c
Why "c" and not "cpp"?

2016-10-17 21:46 UTC, ubruhin commented on .travis.yml
> +  - echo $PWD
What is this for?

2016-10-17 21:46 UTC, ubruhin commented on .travis.yml
> +  - echo $PWD
What is this for?

2016-10-17 22:35 UTC, rnestler commented on .travis.yml
> +language: c
Why anything at all. All that `language: c` does it provides a build environement for C and some default test scripts.

2016-10-17 22:38 UTC, rnestler commented on .travis.yml
> +  - echo $PWD
Just for debugging the build script :wink: wasn't sure about the path were the steps get executed.

2016-10-17 22:57 UTC, ubruhin requested changes

2016-10-17 22:57 UTC, ubruhin commented on .travis.yml
> +  - arduino-$ARDUINO/arduino-builder -hardware arduino-$ARDUINO/hardware -tools arduino-$ARDUINO/tools-builder -tools arduino-$ARDUINO/hardware/tools/avr -fqbn arduino:avr:nano:cpu=atmega328 -warning
Too long line, add line breaks to improve readability.

2016-10-17 23:09 UTC, dns2utf8 commented on .travis.yml
> +    on_success: change
Can we reduce this to never?

2016-10-17 23:21 UTC, rnestler commented on .travis.yml
> +    on_success: change
I don't see why not, I don't use the email notifications anyway.

2016-10-19 10:18 UTC, dns2utf8 commented on .travis.yml
> +    on_success: change
No, the default is set to spam :wink:

2016-10-19 11:20 UTC, dbrgn approved these changes

2016-10-19 12:40 UTC, merged