Added effect SinusRunner2.
coredump-ch/rgb-led-firmware pull request #4
Opened 2016-12-18 17:21 UTC by polovik

Effect SinusRunner2 - every color is changed by SIN. But phase between sinusoids is adjustable.

2016-12-18 23:09 UTC, dns2utf8 requested changes
Thank you for your PR. It looks really good 👍 
Unfortunatly I am currently unable to test it right now. 

What kind of additional hardware did you use?

2016-12-18 23:09 UTC, dns2utf8 commented on src/effect_sinus_runner2.cpp
> +    if(time >= 360.0f) {
Missing space  after if

2016-12-18 23:09 UTC, dns2utf8 commented on src/src.ino
> +    }
Would you mind moving this to a function?

2016-12-19 05:39 UTC, polovik commented
It's strange - I've added only one commit to pull request (941ed7c - "Added effect SinusRunner2 - every color is changed by SIN. But phase between sinusoids is adjustable.") but the second is added too.
I wasn't intent to include the second commit to pull request, because it requeres additional hardware - 1button (for switch effects), 1analog voltage divider (for measure voltage on an accumulator), 1led "L" (for display low charge).

2016-12-19 05:42 UTC, polovik commented on src/effect_sinus_runner2.cpp
> +    if(time >= 360.0f) {
I've copied most source from your code - effect_blue_sin.cpp Therefore somewhere "coding style" was remained.

2016-12-19 05:49 UTC, polovik commented on src/src.ino
> +    }
Please, look at a comment below.

2016-12-19 08:10 UTC, dbrgn commented
No problem, we can cherry-pick your first commit :) Thanks for the contribution!

2016-12-19 08:13 UTC, dbrgn commented
Merged in a43afcd.

2016-12-19 08:13 UTC, closed without merging